"use client";

import { useState, useEffect, useCallback, Suspense } from "react";
import { collection, query, where, getDocs, limit, Timestamp, orderBy, collectionGroup } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { 
  Search, 
  User, 
  ShoppingBag, 
  Loader2, 
  Calendar, 
  MapPin, 
  Phone, 
  Shield, 
  Fingerprint,
  Clock,
  ArrowLeft,
  Store,
  ShoppingCart
} from "lucide-react";
import { useSearchParams, useRouter } from "next/navigation";
import { format } from "date-fns";
import Link from "next/link";

interface UserProfile {
  id: string;
  name?: string;
  displayName?: string;
  email: string;
  status: string;
  createdAt?: any;
  registrationDate?: any; 
  updatedAt?: any;
  location?: string;
  phoneNumber?: string;
  role?: string;
}

interface UserPing {
  id: string;
  createdAt: any;
  status: string;
  amount: number;
  shopId?: string;
  sellerId?: string;
  productId?: string;
  items?: { productId: string }[];
}

interface ResolvedMapping {
  shops: Record<string, string>;
  products: Record<string, { name: string; price: number }>;
}

function UserManagementContent() {
  const [searchTerm, setSearchTerm] = useState("");
  const [foundUser, setFoundUser] = useState<UserProfile | null>(null);
  const [userPings, setUserPings] = useState<UserPing[]>([]);
  const [resolvedData, setResolvedData] = useState<ResolvedMapping>({ shops: {}, products: {} });
  const [loading, setLoading] = useState(false);
  const searchParams = useSearchParams();
  const router = useRouter();

  const handleSearch = useCallback(async (customTerm?: string) => {
    const term = customTerm || searchTerm;
    if (!term) return;
    
    setLoading(true);
    setFoundUser(null);
    setUserPings([]);

    try {
      const usersRef = collection(db, "users");
      // Search by email
      let qUser = query(usersRef, where("email", "==", term), limit(1));
      let snapshot = await getDocs(qUser);

      if (snapshot.empty) {
        // Try searching by ID if email doesn't work
        qUser = query(usersRef, where("id", "==", term), limit(1));
        snapshot = await getDocs(qUser);
      }

      if (!snapshot.empty) {
        const doc = snapshot.docs[0];
        const userData = { id: doc.id, ...doc.data() } as UserProfile;
        setFoundUser(userData);

        // Fetch pings generated by this buyer
        const pingsRef = collection(db, "pings");
        const pingsQuery = query(
          pingsRef, 
          where("buyerId", "==", userData.id), 
          orderBy("createdAt", "desc")
        );
        const pingsSnapshot = await getDocs(pingsQuery);
        const pingData = pingsSnapshot.docs.map(doc => ({
          id: doc.id,
          ...doc.data()
        })) as UserPing[];
        setUserPings(pingData);

        // Resolve Shop and Product details for these pings
        const shopIds = new Set(pingData.map(p => p.shopId || p.sellerId).filter(Boolean) as string[]);
        const productIds = new Set(pingData.map(p => p.items?.[0]?.productId || p.productId).filter(Boolean) as string[]);

        const shopNames: Record<string, string> = {};
        const productDetails: Record<string, { name: string; price: number }> = {};

        // Fetch Shops
        if (shopIds.size > 0) {
          const shopsSnap = await getDocs(collection(db, "shops"));
          shopsSnap.forEach(sDoc => {
            if (shopIds.has(sDoc.id)) {
              shopNames[sDoc.id] = sDoc.data().name || "Unknown Shop";
            }
          });
        }

        // Fetch Products
        if (productIds.size > 0) {
          const productsSnap = await getDocs(collectionGroup(db, "products"));
          productsSnap.forEach(pDoc => {
            if (productIds.has(pDoc.id)) {
              productDetails[pDoc.id] = {
                name: pDoc.data().name || "Unknown Product",
                price: pDoc.data().price || 0
              };
            }
          });
        }

        setResolvedData({ shops: shopNames, products: productDetails });
      }
    } catch (error) {
      console.error("Error searching user or fetching pings:", error);
    } finally {
      setLoading(false);
    }
  }, [searchTerm]);

  // Handle search parameter from URL
  useEffect(() => {
    const urlSearch = searchParams.get("search");
    if (urlSearch) {
      setSearchTerm(urlSearch);
      handleSearch(urlSearch);
    }
  }, [searchParams, handleSearch]);

  const formatDate = (date: any) => {
    if (!date) return "N/A";
    const d = date instanceof Timestamp ? date.toDate() : new Date(date);
    try {
      return format(d, "MMM d, yyyy HH:mm");
    } catch {
      return "Invalid Date";
    }
  };

  const getStatusBadge = (status: string) => {
    const s = (status || "").toLowerCase().trim();
    if (s === 'successful' || s === 'completed' || s === 'success') return <Badge className="bg-emerald-500/10 text-emerald-500 border-emerald-500/20">Successful</Badge>;
    if (s === 'pending') return <Badge variant="secondary" className="bg-amber-500/10 text-amber-500 border-amber-500/20">Pending</Badge>;
    if (s === 'confirmed') return <Badge className="bg-blue-500/10 text-blue-500 border-blue-500/20">Confirmed</Badge>;
    if (s === 'cancelled') return <Badge variant="destructive" className="bg-destructive/10 text-destructive border-destructive/20">Cancelled</Badge>;
    return <Badge variant="outline">{status}</Badge>;
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-headline font-bold text-foreground tracking-tight">User Administration</h1>
          <p className="text-muted-foreground mt-1 text-lg">Detailed profile inspection and transaction auditing.</p>
        </div>
        {foundUser && (
          <Button variant="outline" size="sm" onClick={() => { setFoundUser(null); setSearchTerm(""); router.push('/admin/users'); }}>
            <ArrowLeft className="mr-2 h-4 w-4" /> Clear View
          </Button>
        )}
      </div>

      <div className="flex gap-4 max-w-xl">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input 
            placeholder="Search by email or user ID..." 
            className="pl-10 h-11"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          />
        </div>
        <Button onClick={() => handleSearch()} disabled={loading} size="lg">
          {loading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : "Search"}
        </Button>
      </div>

      {foundUser ? (
        <div className="flex flex-col gap-8 max-w-5xl mx-auto">
          {/* Identity Dossier Card */}
          <Card className="border-border bg-card/40 backdrop-blur">
            <CardHeader className="pb-4 border-b border-border/50">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <User className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <CardTitle className="text-xl">Identity Dossier</CardTitle>
                  <CardDescription>Verified system records for account {foundUser.id.slice(0, 8)}</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8">
                {/* Basic Info */}
                <div className="space-y-6">
                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                      <User className="h-3 w-3" /> Full Name (displayName)
                    </p>
                    <p className="text-lg font-bold text-foreground">
                      {foundUser.displayName || "N/A"}
                    </p>
                  </div>

                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                      <Calendar className="h-3 w-3" /> Email Address
                    </p>
                    <p className="text-sm font-medium text-foreground">
                      {foundUser.email}
                    </p>
                  </div>

                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                      <Fingerprint className="h-3 w-3" /> UID Reference
                    </p>
                    <code className="text-[11px] font-mono bg-muted/50 px-1.5 py-0.5 rounded text-muted-foreground">
                      {foundUser.id}
                    </code>
                  </div>

                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                      <Shield className="h-3 w-3" /> System Role
                    </p>
                    <Badge variant="outline" className="font-semibold text-primary border-primary/20 bg-primary/5">
                      {foundUser.role || "User"}
                    </Badge>
                  </div>
                </div>

                {/* Contact & Status */}
                <div className="space-y-6">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                        <Phone className="h-3 w-3" /> Phone
                      </p>
                      <p className="text-sm font-medium">{foundUser.phoneNumber || "None set"}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                        <MapPin className="h-3 w-3" /> Location
                      </p>
                      <p className="text-sm font-medium truncate" title={foundUser.location}>
                        {foundUser.location || "None set"}
                      </p>
                    </div>
                  </div>

                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                      <Clock className="h-3 w-3" /> Registered Date
                    </p>
                    <p className="text-sm font-medium">{formatDate(foundUser.createdAt || foundUser.registrationDate)}</p>
                  </div>

                  <div className="space-y-1">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest flex items-center gap-1.5">
                      <Clock className="h-3 w-3" /> Last Updated
                    </p>
                    <p className="text-sm font-medium">{formatDate(foundUser.updatedAt)}</p>
                  </div>

                  <div className="pt-2">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mb-1.5">Account Status</p>
                    <Badge className={foundUser.status === "Active" ? "bg-emerald-500/10 text-emerald-500 hover:bg-emerald-500/20 border-emerald-500/20" : "bg-destructive/10 text-destructive hover:bg-destructive/20 border-destructive/20"}>
                      {foundUser.status}
                    </Badge>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Purchase Audit History Card */}
          <Card className="border-border bg-card/40 backdrop-blur">
            <CardHeader className="border-b border-border/50">
              <div className="flex items-center gap-2">
                <ShoppingBag className="h-5 w-5 text-primary" />
                <CardTitle className="text-xl">Purchase Audit History</CardTitle>
              </div>
              <CardDescription>Resolved transaction history across all merchants.</CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader className="bg-muted/30">
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Shop Name</TableHead>
                    <TableHead>Product Details</TableHead>
                    <TableHead>Price</TableHead>
                    <TableHead className="text-right">Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {userPings.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={5} className="h-48 text-center text-muted-foreground">
                        <div className="flex flex-col items-center justify-center gap-2">
                          <ShoppingBag className="h-10 w-10 opacity-20" />
                          <p>No transaction pings found for this identity.</p>
                        </div>
                      </TableCell>
                    </TableRow>
                  ) : (
                    userPings.map((ping) => {
                      const shopId = ping.shopId || ping.sellerId || "";
                      const productId = ping.items?.[0]?.productId || ping.productId || "";
                      const shopName = resolvedData.shops[shopId] || "Unknown Shop";
                      const productInfo = resolvedData.products[productId] || { name: "Unknown Item", price: 0 };

                      return (
                        <TableRow key={ping.id} className="hover:bg-muted/20 transition-colors">
                          <TableCell className="text-xs font-medium text-muted-foreground">
                            {formatDate(ping.createdAt)}
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-2">
                              <Store className="h-3 w-3 text-muted-foreground" />
                              <span className="font-medium">{shopName}</span>
                            </div>
                          </TableCell>
                          <TableCell>
                            <div className="flex items-center gap-2">
                              <ShoppingCart className="h-3 w-3 text-primary/60" />
                              <span className="text-sm">{productInfo.name}</span>
                            </div>
                          </TableCell>
                          <TableCell className="font-bold text-primary">
                            ${(productInfo.price || ping.amount || 0).toLocaleString()}
                          </TableCell>
                          <TableCell className="text-right">
                            {getStatusBadge(ping.status)}
                          </TableCell>
                        </TableRow>
                      );
                    })
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      ) : (
        !loading && searchTerm && (
          <div className="text-center py-24 bg-muted/20 rounded-2xl border border-dashed border-border/60">
            <User className="h-16 w-16 text-muted-foreground/30 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-muted-foreground">No Account Found</h3>
            <p className="text-sm text-muted-foreground/80 mt-1">Verify the email address or UID and try again.</p>
          </div>
        )
      )}
    </div>
  );
}

export default function UsersPage() {
  return (
    <Suspense fallback={
      <div className="flex flex-col items-center justify-center h-96 gap-4">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
        <p className="text-sm text-muted-foreground animate-pulse">Retrieving user profile data...</p>
      </div>
    }>
      <UserManagementContent />
    </Suspense>
  );
}
